name: 'ðŸš€ Build and deploy'

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:
    inputs:
      tag:
        default: main
        name: Download tag
        type: string

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BUILDABLE: '["01.create-react-app", "06.esbuild", "07.a.webpack4-cjs", "07.b.webpack4-esm", "08.webpack5"]'

jobs:
  download-tarball:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ./download-tag.sh ${{ inputs.tag || 'latest' }}
        working-directory: drops

      - name: Upload tarballs
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: tarball
          path: |
            drops/
            !drops/.gitignore
            !drops/*.sh

  build:
    name: Build
    needs:
      - download-tarball
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildable: ${{ fromJSON(env.BUILDABLE) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Download tarball
        uses: actions/download-artifact@v7
        with:
          name: tarball
          path: drops/

      - run: npm clean-install
        working-directory: ${{ matrix.buildable }}

      - run: ./install-drops.sh
        working-directory: ${{ matrix.buildable }}

      - run: npm run build
        working-directory: ${{ matrix.buildable }}

      - if: matrix.buildable == '01.create-react-app'
        name: Rename build/ to public/
        run: mv build public
        working-directory: 01.create-react-app

      - name: Move build output
        run: |
          mkdir -p artifact/${{ matrix.buildable }}
          mv ${{ matrix.buildable }}/public artifacts
          mv artifacts/public artifacts/${{ matrix.buildable }}
          echo $(date) > artifact/build-${{ matrix.buildable }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: build-${{ matrix.buildable }}
          path: artifact/

  build-pages:
    needs:
      - build-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove buildables
        run:
          echo ${{ env.BUILDABLE }} | jq .[] | xargs rm -r

      - uses: actions/download-artifact@v7
        with:
          name: build-*
          merge-multiple: true

      - uses: actions/upload-pages-artifact@v4
        with:
          path: .
