name: 'ðŸš€ Build and deploy'

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:
    inputs:
      tag:
        default: main
        name: Download tag
        type: string

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BUILDABLE: '["01.create-react-app", "06.esbuild", "07.a.webpack4-cjs", "07.b.webpack4-esm", "08.webpack5"]'

jobs:
  prepare:
    name: Prepare
    outputs:
      buildable: ${{ steps.dump.outputs.buildable }}
    runs-on: ubuntu-latest

    steps:
      - id: dump
        run: echo 'buildable=${{ env.BUILDABLE }}' | tee --append $GITHUB_OUTPUT

  download-tarball:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ./download-tag.sh ${{ inputs.tag || 'latest' }}
        working-directory: drops

      - name: Upload tarballs
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: tarball
          path: |
            drops/
            !drops/.gitignore
            !drops/*.sh

  build-package:
    name: Build package
    needs:
      - download-tarball
      - prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildable: ${{ fromJSON(needs.prepare.outputs.buildable) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Download tarball
        uses: actions/download-artifact@v7
        with:
          name: tarball
          path: drops/

      - run: npm clean-install
        working-directory: ${{ matrix.buildable }}

      - run: ./install-drops.sh
        working-directory: ${{ matrix.buildable }}

      - run: npm run build
        working-directory: ${{ matrix.buildable }}

      - if: matrix.buildable == '01.create-react-app'
        name: Rename build/ to dist/
        run: mv build/ dist/
        working-directory: ${{ matrix.buildable }}

      - if: matrix.buildable != '01.create-react-app'
        name: Rename public/ to dist/
        run: mv public/ dist/
        working-directory: ${{ matrix.buildable }}

      - name: Move build output
        run: |
          mkdir -p artifact/
          mv ${{ matrix.buildable }}/dist/ artifact/
          mv artifact/dist/ artifact/${{ matrix.buildable }}/
          echo $(date) > artifact/build-${{ matrix.buildable }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: build-${{ matrix.buildable }}
          path: artifact/

  build-bundle:
    name: Build bundle
    needs:
      - download-tarball
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Download tarball
        uses: actions/download-artifact@v7
        with:
          name: tarball
          path: drops/

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: build-bundle
          path: |
            drops/
            !drops/.gitignore
            !drops/*.sh
            !drops/*.tgz

  build-pages:
    name: Build pages
    needs:
      - build-bundle
      - build-package
      - prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove buildables
        run: |
          echo '${{ needs.prepare.outputs.buildable }}' | jq .[] | xargs rm -r
          ls -la

      - uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: build-*

      - uses: actions/upload-pages-artifact@v4
        with:
          path: .

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    name: Deploy pages
    needs:
      - build-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
